### ISSUE TITLE
TGGuidanceViewController is not getting initialise 

### ISSUE THREAD

**Issue by jasvir9013** [tallygo/TallyGoKit#10]
When I try to initialise TGGuidanceViewController using 
let viewController = TGGuidanceViewController.makeFromStoryboard()
it gives me crash with error msg
Message from debugger: Terminated due to signal 9

**Comment by dmdeller** [comment]
It seems that this can happen when attempting to use the SDK outside of our supported service area. We will improve handling of this condition in a future version.
