### ISSUE TITLE
spell check on the docs ?

### ISSUE THREAD

**Issue by jeis2497052** [tallygo/TallyGoKit#11]
Hi All,

I would to propose some spelling corrections below:

diff --git a/Documentation/Classes/TGButton.html b/Documentation/Classes/TGButton.html
index 7e485e0..5871155 100644
--- a/Documentation/Classes/TGButton.html
+++ b/Documentation/Classes/TGButton.html
@@ -457,7 +457,7 @@
                     <section class="section">
                       <div class="pointer"></div>
                       <div class="abstract">
-                        <p>Redraws the button when the subviews are layed out.</p>
+                        <p>Redraws the button when the subviews are layered out.</p>
 
                       </div>
                       <div class="declaration">
diff --git a/Documentation/Classes/TGTurnByTurnViewController.html b/Documentation/Classes/TGTurnByTurnViewController.html
index 23c40a9..60acae0 100644
--- a/Documentation/Classes/TGTurnByTurnViewController.html
+++ b/Documentation/Classes/TGTurnByTurnViewController.html
@@ -1024,7 +1024,7 @@
                     <section class="section">
                       <div class="pointer"></div>
                       <div class="abstract">
-                        <p>Override point to perform addtional layout tasks. Default implementation does nothing.</p>
+                        <p>Override point to perform additional layout tasks. Default implementation does nothing.</p>
 
                       </div>
                       <div class="declaration">
diff --git a/Documentation/Protocols/TGSearchViewControllerDelegate.html b/Documentation/Protocols/TGSearchViewControllerDelegate.html
index 0698a3e..41ef74c 100644
--- a/Documentation/Protocols/TGSearchViewControllerDelegate.html
+++ b/Documentation/Protocols/TGSearchViewControllerDelegate.html
@@ -581,7 +581,7 @@
                     <section class="section">
                       <div class="pointer"></div>
                       <div class="abstract">
-                        <p>Override this function to be notified when the user begin interacting with the search text field. The default implementaion does nothing.</p>
+                        <p>Override this function to be notified when the user begin interacting with the search text field. The default implementation does nothing.</p>
 
                       </div>
                       <h4>Default<C2><A0>Implementation</h4>
@@ -642,7 +642,7 @@
                     <section class="section">
                       <div class="pointer"></div>
                       <div class="abstract">
-                        <p>Override this function to be notified when the user presses the cancel button. The default implementaion does nothing.</p>
+                        <p>Override this function to be notified when the user presses the cancel button. The default implementation does nothing.</p>
 
                       </div>
                       <h4>Default<C2><A0>Implementation</h4>
diff --git a/Documentation/docsets/TallyGoKit.docset/Contents/Resources/Documents/Classes/TGButton.html b/Documentation/docsets/TallyGoKit.docset/Contents/Resources/Documents/Classes/TGButton.html
index 7e485e0..5871155 100644
--- a/Documentation/docsets/TallyGoKit.docset/Contents/Resources/Documents/Classes/TGButton.html
+++ b/Documentation/docsets/TallyGoKit.docset/Contents/Resources/Documents/Classes/TGButton.html
@@ -457,7 +457,7 @@
                     <section class="section">
                       <div class="pointer"></div>
                       <div class="abstract">
-                        <p>Redraws the button when the subviews are layed out.</p>
+                        <p>Redraws the button when the subviews are layered out.</p>
 
                       </div>
                       <div class="declaration">
rnViewController.html
index 23c40a9..60acae0 100644
--- a/Documentation/docsets/TallyGoKit.docset/Contents/Resources/Documents/Classes/TGTurnByTurnViewController.html
+++ b/Documentation/docsets/TallyGoKit.docset/Contents/Resources/Documents/Classes/TGTurnByTurnViewController.html
@@ -1024,7 +1024,7 @@
                     <section class="section">
                       <div class="pointer"></div>
                       <div class="abstract">
-                        <p>Override point to perform addtional layout tasks. Default implementation does nothing.</p>
+                        <p>Override point to perform additional layout tasks. Default implementation does nothing.</p>
 
                       </div>
                       <div class="declaration">
SearchViewControllerDelegate.html
index 0698a3e..41ef74c 100644
--- a/Documentation/docsets/TallyGoKit.docset/Contents/Resources/Documents/Protocols/TGSearchViewControllerDelegate.html
+++ b/Documentation/docsets/TallyGoKit.docset/Contents/Resources/Documents/Protocols/TGSearchViewControllerDelegate.html
@@ -581,7 +581,7 @@
                     <section class="section">
                       <div class="pointer"></div>
                       <div class="abstract">
-                        <p>Override this function to be notified when the user begin interacting with the search text field. The default implementaion does nothing.</p>
+                        <p>Override this function to be notified when the user begin interacting with the search text field. The default implementation does nothing.</p>
 
                       </div>
                       <h4>Default<C2><A0>Implementation</h4>
@@ -642,7 +642,7 @@
                     <section class="section">
                       <div class="pointer"></div>
                       <div class="abstract">
-                        <p>Override this function to be notified when the user presses the cancel button. The default implementaion does nothing.</p>
+                        <p>Override this function to be notified when the user presses the cancel button. The default implementation does nothing.</p>
 
                       </div>
                       <h4>Default<C2><A0>Implementation</h4>

There may be some json file updates that are also needed.

**Comment by dmdeller** [comment]
Thanks for finding these! We will fix in an upcoming version of the SDK.

**Comment by jeis2497052** [comment]
glad to contribute David

**Comment by mtriplett** [comment]
Fixed in upcoming 2.0 release of iOS SDK.
