### ISSUE TITLE
Routing not calculating properly when there are roundabouts implicated.

### ISSUE THREAD

**Issue by alexdevgit** [tallygo/TallyGoKit#13]
Hi there team.
I just got feedback from one user saying that navigation feature is avoiding roundabouts and was routing them on and off the highway to avoid them. This is happening in Vail, Colorado, specifically from Vail Fire Department Station3 to 4695 Vail Racquet Club Dr, Vail, CO 81657, EE. UU.
Here is that route calculated with Google Maps
<img width="1280" alt="captura de pantalla 2018-03-28 a la s 14 22 14" src="https://user-images.githubusercontent.com/17258541/38048596-d2a3fa02-3293-11e8-90c2-20addbb9b549.png">

and here is the same route calculated with TallyGo's SDK

![img_0037](https://user-images.githubusercontent.com/17258541/38048528-a11b5368-3293-11e8-955c-a3847256ad5f.PNG)

Would appreciate any update from your team. Thanks in advance!

**Comment by mtriplett** [comment]
Hi Alex, let me check into this for you. Stay tuned.

**Comment by mtriplett** [comment]
Alex, we’ve just deployed a fix that should resolve this issue. No changes required on your end. BTW, this issue wasn't actually related to roundabouts (although it may have appeared that way), there was more to it than that. But in any case, it should be fixed now.

Let me know if you have any more trouble.

**Comment by alexdevgit** [comment]
Hi Mat! Just tried on those same locations and it's fine now! Thank you and the team very much!
![img_0039](https://user-images.githubusercontent.com/17258541/38444859-051240fc-39bf-11e8-930c-f3d92aac7e9b.PNG)

**Comment by mtriplett** [comment]
Awesome, thanks for the update!
