### ISSUE TITLE
Can't use the framework with Xcode 9

### ISSUE THREAD

**Issue by rlaguilar** [tallygo/TallyGoKit#4]
When importing the framework Xcode 9 throws an error saying that "Module compiled with Swift 3.1 can't be imported in Swift 3.2".
Can you provide a new framework compatible with Xcode 9?

**Comment by picciano** [comment]
We will have a Xcode 9 compatible release in early October. We appreciate your patience. Thanks!

**Comment by picciano** [comment]
Resolved with SDK 1.4.0.
