### ISSUE TITLE
Strange blinking in the map

### ISSUE THREAD

**Issue by rlaguilar** [tallygo/TallyGoKit#5]
From time to time the map blinks causing a bad UX, it seems something related to the styles being loading multiple times or something like that. Any hints about how to solve that?

**Comment by jbTallyGo** [comment]
Hi rlaguilar. This is a known issue which we have queued up to be fixed in the near future.  A release date for the fix is still TBD.

**Comment by konakuo** [comment]
Hi, This is Chin with Locality Media/First Due Sizeup, our app uses your SDK and we released it for testing with our users. A few important users reported that the map is disappearing. They have to close the app and reopen. Do you think it is related to this problem or we need to create a new issue? Looking to have resolution or help understand how to gather more information that can help you to investigate. Thanks.

**Comment by mtriplett** [comment]
This has been resolved in version 1.7.0 of the TallyGo SDK.
