### ISSUE TITLE
TGGuidanceViewController stops updating the user position after checking the Route Overview

### ISSUE THREAD

**Issue by rlaguilar** [tallygo/TallyGoKit#6]
When you consult the Route Overview in the `TGGuidanceViewController` the position of the user (using the driving simulator) stops being updated. Steps to reproduce in the sample Swift app:
1. Start navigating a route
2. Press the Menu button
3. Go to *Route Overview*
4. Go back to the menu
5. Press the done button.

Once you are again in the `TGGuidanceViewController` it doesn't update the user position.

**Comment by picciano** [comment]
This is a known issue when running using the driving simulator. We are working to get this resolved. No planned release date yet for this one.

**Comment by mtriplett** [comment]
This has been resolved in version 1.7.0 of the TallyGo SDK.
