### ISSUE TITLE
Too many bug for accessing private object

### ISSUE THREAD

**Issue by jasvir9013** [tallygo/TallyGoKit#8]
![screen shot 2017-11-09 at 5 50 17 pm](https://user-images.githubusercontent.com/23275068/32605197-869911c2-c576-11e7-9017-0db89df95109.png)

**Comment by picciano** [comment]
Recent versions of TallyGoKit have removed the dependency on CryptoSwift. Please update.

**Comment by jasvir9013** [comment]
I just download your project from github and run command pod install. It automatically install the CrytoSwift. Should I remove this framework ?

**Comment by picciano** [comment]
Do a `pod update`. CryptoSwift should be removed by doing so.

**Comment by jasvir9013** [comment]
Ok, I will check that by tomorrow. Thanks for your quick response. really appreciate :)
